### ISSUE TITLE
Stop sending emails when disabled

### ISSUE THREAD

**Issue by christofferengstrom** [microsoft/appcenter#1112]
**Describe the solution you'd like**
Stop sending emails when a user have disabled email notifications.

**Describe alternatives you've considered**
To add a link to unsubscribe within the email.

**Additional context**
I receive an email every time my colleague moves an app from HockeyApp to App Center, even if I have disabled email notifications in both HockeyApp and App Center.

**Comment by blparr** [comment]
So sorry to hear that you are experience this. I notified the team and we will try to fix this issue asap.

Thank you for making us aware!

**Comment by nathanhillyer** [comment]
@blparr @ScottArbeit Any update to share on this issue? We are migrating dozens of apps and aren't able to disable the emails for our team.

**Comment by ScottArbeit** [comment]
@nathanhillyer @christofferengstrom I apologize for the delay, and I've started a chat within the team to get context.

A few questions so I can share the info: where have you each disabled email notifications in HockeyApp and App Center? Have you done it in App Center at the App Settings level? At the individual App Center user level? And where in HockeyApp?

**Comment by derpixeldan** [comment]
@christofferengstrom yes, the email notification once an app was moved successfully is sent regardless of the notification settings. We're looking into improving this. Sorry for the inconvenience.

**Comment by nathanhillyer** [comment]
@derpixeldan Do you need the information requested by Scott above? The short answer is we tried to disable them everywhere, but are still getting the emails, but I can address the individual questions more thoroughly if needed.

**Comment by derpixeldan** [comment]
@nathanhillyer no thanks, we're good.

**Comment by derpixeldan** [comment]
We deployed a fix and the success emails will not be sent anymore when notifications are disabled in HockeyApp.

**Comment by nathanhillyer** [comment]
@derpixeldan I have notifications disabled for both HockeyApp and AppCenter, but I still receive emails. I disabled here: https://rink.hockeyapp.net/manage/notifications

Is there another spot to disable?
