### ISSUE TITLE
Xamarin.UITest to automatically dismiss springboard alerts in Simplified Chinese and Traditional Chinese

### ISSUE THREAD

**Issue by pi-leo-liu** [microsoft/appcenter#1925]
**Describe the solution you'd like**
Please refer to this ticket raised against DeviceAgent:
https://github.com/calabash/run_loop/issues/753

When running automation using Xamarin.UITest 3.0.7 against an iPhone with its language being set to Simplified Chinese or Traditional Chinese, the springboard alerts are not automatically dismissed. It covers on top of screens where it causes all our tests to fail. Raise this against DeviceAgent, but it looks like DeviceAgent does support this. Then raise it against the app center support  then the support guy asked me to create a new feature request for this.

Note this issue does not occurs on any other languages including Spanish, German, French etc...

**Comment by IlyaBausovAkvelon** [comment]
Hello,

@pi-leo-liu could you please try to use 3.0.13 Xamarin.UITest framework version?
Seems like the issue should be resolved now.

Thanks,
Ilya

**Comment by pi-leo-liu** [comment]
Hi llya,

I can confirm that the issue is still there in 3.0.17 Xamarin.UITest framework. I do not think it has been fixed.
Can you please let me know when this will be addressed?

Thanks,

Regards,

Leo



________________________________
