### ISSUE TITLE
Xamarin.UITest: Problems with .NET Core 3.1 / .NET 5 & UITests on iOS

### ISSUE THREAD

**Issue by markuskoehlersofa** [microsoft/appcenter#2280]
Hello Microsoft,

we want to use Xamarin.UITest to test our apps with Android and iOS. But this does not work and depending on the version of Xamarin.UITest, there are different problems:

1. **For versions <= 3.0.15:** Xamarin.UITest.XDB.Exceptions.DeviceAgentException (Failed to install DeviceAgent, ExitCode: 134) on calling ConfigureApp.iOS.InstalledApp("...").StartApp(Xamarin.UITest.Configuration.AppDataMode.DoNotClear).
See also issue #829 (which showed a similar problem)
2. **For versions >= 3.0.8:** When using Target Framework netcoreapp3.1 or net5.0 in the project that uses Xamarin.UITest, when using this package, it is not found.
See also issue #2148 (which requested support for those frameworks, but still does not work)

### Details
**Hardware/Software**

- macOS Big Sur version 11.0.1
- JetBrains Rider 2021.2.1
- Xcode 12.5.1

**Problem 1**
The full exception was (on version 3.0.15)
```
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to install DeviceAgent

ExitCode: 134
...
*** First throw call stack:
2021-09-15 15:49:24.603 iOSDeviceManager[59090:320806] *** Assertion failure in -[FBDeviceControlFrameworkLoader_Xcode loadPrivateFrameworksOrAbort], FBControlCoreFrameworkLoader.m:84
2021-09-15 15:49:24.605 iOSDeviceManager[59090:320806] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to load private frameworks for FBSimulatorControl with error Error Domain=com.facebook.FBControlCore Code=0 "Attempting to load a file at path '/Applications/Xcode.app/Contents/Frameworks/DFRSupportKit.framework', but it does not exist" UserInfo={NSLocalizedDescription=Attempting to load a file at path '/Applications/Xcode.app/Contents/Frameworks/DFRSupportKit.framework', but it does not exist}'
libc++abi.dylib: terminating with uncaught exception of type NSException
  at Xamarin.UITest.XDB.Services.iOSDeviceAgentService.WithErrorHandling (System.Int32 eventId, System.Func`1[TResult] action, System.String errorMessage, System.Int32[] successCodes) [0x000b8] in <aaa0e77bd69d4afdb45dee891dfe25de>:0 
  at Xamarin.UITest.XDB.Services.iOSDeviceAgentService.LaunchTestAsync (System.String deviceId, System.String deviceAddress) [0x002ab] in <aaa0e77bd69d4afdb45dee891dfe25de>:0 
  at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Http.HttpClient httpClient, System.Boolean clearAppData) [0x001e3] in <aaa0e77bd69d4afdb45dee891dfe25de>:0 
  at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Http.HttpClient httpClient, Xamarin.UITest.TestCloud.TestCloudiOSAppConfiguration testCloudAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient testCloudWsClient, Xamarin.UITest.Shared.Http.HttpClient xtcServicesClient, System.Boolean testCloudUseDeviceAgent) [0x00068] in <aaa0e77bd69d4afdb45dee891dfe25de>:0 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Execution.IExecutor executor) [0x0026f] in <aaa0e77bd69d4afdb45dee891dfe25de>:0 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration) [0x00000] in <aaa0e77bd69d4afdb45dee891dfe25de>:0 
  at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp (Xamarin.UITest.Configuration.AppDataMode appDataMode) [0x00017] in <aaa0e77bd69d4afdb45dee891dfe25de>:0 
  at ... (local code)
```

**Comment by Jeanjean** [comment]
Both issues mentioned and referenced here have been closed by bots. Valuable community feedback seems to go wasted because of insufficient resources for these products. Having bots close unresolved issues does not clean up your backlog. It will however result in developers not even bothering in filling issues or commenting on open issues which in turn causes bots to close issues due to inactivity. This rapidly spirals down and will ultimately cause more and more developers to turn their backs to these products in favour of more stable solutions. And that is a shame as these products (UITest and App Center) are great when they work. However increasingly so UITest has been very difficult to work with to the point where now it has been become impossible. One questions if the cost of writing and maintaining tests is worth it at this point. 

I understand the development team has been very busy with .Net 6, but we still rely on these tools in production. So I would like to urge MS to at least properly manage the issues we report and give us some perspective on what the plans are for these projects in terms of roadmap and resource allocation if MS continues to see a place for these products in the new .Net ecosystem. If not then that needs to be made clear to us so we can take the necessary steps. 

I sincerely hope someone at MS is reading is and that we can read some answers. Thank you.

**Comment by jameslavery** [comment]
I'm having the same problem. Means we can't run UITests on iOS.

**Comment by AlexeyBudynkov** [comment]
> I'm having the same problem. Means we can't run UITests on iOS.
> 
> * macOS Monterey 12.6
> * JetBrains Rider 2022.2.3
> * Xcode 14.0.1
> * Xamarin.UITest 3.12.0

Hello. May you, please, specify what Xamarin.UITest version you use?
Because there is no such version as 3.12.0. The last available version is 3.2.9

**Comment by AlexeyBudynkov** [comment]
> I'm having the same problem. Means we can't run UITests on iOS.
> 
> * macOS Monterey 12.6
> * JetBrains Rider 2022.2.3
> * Xcode 14.0.1
> * Xamarin.UITest 3.12.0

And also, for what iOS version you use?

**Comment by jameslavery** [comment]
@AlexeyBudynkov Thank you for your observation - I mis-typed the UITest version.

Xamarin.UITest 3.2.9
iOS 15.4.1

**Comment by AlexeyBudynkov** [comment]
> @AlexeyBudynkov Thank you for your observation - I mis-typed the UITest version.
> 
> Xamarin.UITest 3.2.9 iOS 15.4.1

The problem still exists? I mean, do you still see the error Failed to install DeviceAgent?

**Comment by jameslavery** [comment]
> > @AlexeyBudynkov Thank you for your observation - I mis-typed the UITest version.
> > Xamarin.UITest 3.2.9 iOS 15.4.1
> 
> The problem still exists? I mean, do you still see the error Failed to install DeviceAgent?

Yes - the same error with "Failed to load private frameworks for FBSimulatorControl..." in the details

**Comment by AlexeyBudynkov** [comment]
We're working on it and it should be fixed in the next Xamarin.UITest release

**Comment by jameslavery** [comment]
Great - thank you.

You know my next question...

Do you have a timeline for the next release?
________________________________

**Comment by JohnHDev** [comment]
@AlexeyBudynkov 
The Xamarin.UITest version has moved on several times since this issue was reported, and it still fails with 'failed to install DeviceAgent' (after having to manually install the .app via cli, as that doesn't work either). This is on macOS-12 Azure DevOps build hosts, so Xcode 14+.

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev Hi,
I've answered about it here: https://github.com/microsoft/appcenter/issues/2475/

**Comment by DmitriyKirakosyan** [comment]
Closing. Please let me know if anyone still faces this issue.
