### ISSUE TITLE
Xamarin.UITest does not run on a physical iOS device with OS versions 16.0.0 - 17.0.0 when updating Xcode version 14.1.0 - 15.0 and Visual Studio for mac version 17.6.5(VS for mac 2022 build 417)

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2475]
Xamarin.UITest does not run on iOS when updating Xcode version 14.1.0 - 15.0 and Visual Studio for Mac version 17.6.5(VS for Mac 2022 build 417) 0r VS for Mac 2019. When running the tests on a physical (not simulator)ios device with these updates you get the following error:

`"Xamarin.UITest.XDB.Exceptions.DeviceAgentException: Failed to launch DeviceAgent"`

This is with Xamarin.UITest version 3.2.9-4.3.0, a new Xamarin.UITest version needs to come out to handle the new Xcode and VS for Mac updates.

**Comment by IlyaBausovAkvelon** [comment]
Hi @Moshex. Thank you for a feedback.
Please wait for an update when the new version will be released.

**Comment by Moshex** [comment]
@IlyaBausovAkvelon 
I was able to fix the "DeviceAgent" issue however on iPhone iOS version 16  Xamarin.UITest is not able to enter text

**Comment by sjavashev** [comment]
> @IlyaBausovAkvelon I was able to fix the "DeviceAgent" issue however on iPhone iOS version 16 Xamarin.UITest is not able to enter text and I get the error of:
> 
> ```
> System.Exception : Error while performing ClearText(Marked("EmailEntry"))
>   ----> System.TimeoutException : Timed out waiting for keyboard.
> ```

You can try replacing EnterText calls with invoke on setText - something like the below:
```
app.Tap(field);
app.Query(x => field(x).Class("UITextField").Invoke("setText", text));

```

However I couldn't find a way to solve the Picker selection - for example Date or Time...

**Comment by Moshex** [comment]
@sjavashev Honestly, I know about invoking text but rather than making a framework change to use invoke we really just need an update to Xamarin.UITest for iOS 16 devices. Thank you so much for joining the thread and helping to push the Xamarin.UITest team for a fix.

**Comment by Yevhen-Myroshnychenko** [comment]
In my case, It looks like Xamarin.UITest can't interact with the Entry (can't clear existing text or can't enter the new one). In this situation it is impossible to run tests on iOS emulator. On Android everything works fine.
I'm using: 
- VS 2020 for Mac OS - 17.3.7 (build 1) 
- Xamarin project: NETStandart.Library 2.1.0 with Xamarin.Forms 4.8.0.1821
- Xamarin.UITest project: NUnit 3.13.3, NUnitTestUdapter 4.2.1, Xamarin.UITest 3.2.9 

On IOS emulator I get: System.Exception : Error while performing EnterText(Marked("ActivationEntry"), ".someText")
  ----> System.TimeoutException : Timed out waiting for keyboard.
Also I get the same issue as this topic describes whenever I try to Clear text placed in the Entry.

**Comment by IlyaBausovAkvelon** [comment]
Hi all!
We've fixed this in the next release. Please wait for it.
Thank you.

**Comment by JohnHDev** [comment]
> Hi all!
> We've fixed this in the next release. Please wait for it.
> Thank you.

When might that be? Would be great to get this fix out asap, as you can see there are *many* UI tests, for *many* companies using Xamarin UITest that are now broken, waiting for MS to add support for software that released over a month ago.

Or is this running on the same schedule as .NET 6 support for the Xamarin Test Cloud nuget? Thursday after never?

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon any news on this? You mentioned you had a fix 20 days ago but it still isn't released.
Can you provide a timeline?

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon I see there is a new version of Xamarin.UITest nuget, v 4.0!

Unfortunately it is throwing an exception:
The type initializer for 'Xamarin.UITest.ConfigureApp' threw an exception

**Comment by JohnHDev** [comment]
Exception is: Could not load file or assembly 'Xamarin.UITest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by IlyaBausovAkvelon** [comment]
Hi all! We know about issue with assembly missing. We are working on fixing that. We will release a patch soon.
Thank you for the feedback!

**Comment by Moshex** [comment]
@IlyaBausovAkvelon 

Thank you for the heads up I am seeing the issue you are talking about with Xamarin.UITest version 4.0.0

This is the error:
```
System.TypeInitializationException : The type initializer for 'WellRx.UITests.Helper.AppConstants' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Xamarin.UITest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

**Comment by Moshex** [comment]
@IlyaBausovAkvelon
iPhone iOS version 16 Xamarin.UITest is not able to enter text and this issue is still open on Xamarin.UITest version 4.0.1,
The I get the error of:

```
System.Exception : Error while performing ClearText(Marked("EmailEntry"))
  ----> System.TimeoutException : Timed out waiting for keyboard.
```

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon it appears that 4.0.1 is no better than 3.2.9, so we are 2 months in since @Moshex reported this and we are no closer to a fix.
Do you have a fresh ETA for this? You did say you (MS) had fixed this.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon um, why is 4.0.1 generating TinyiOC.cs files in my test projects?

**Comment by akrol95** [comment]
> @IlyaBausovAkvelon iPhone iOS version 16 Xamarin.UITest is not able to enter text and this issue is still open on Xamarin.UITest version 4.0.1, The I get the error of:
> 
> ```
> System.Exception : Error while performing ClearText(Marked("EmailEntry"))
>   ----> System.TimeoutException : Timed out waiting for keyboard.
> ```

I'm facing exact the same error with 4.0.1

**Comment by rory-bloomerang** [comment]
Is there any update on this? Still seeing the same issue mentioned in the original post on 4.0.1.

`"Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent"`

**Comment by Moshex** [comment]
> Is there any update on this? Still seeing the same issue mentioned in the original post on 4.0.1.
> 
> `"Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent"`

To fix that error all I needed to do was to delete the Device Agent app on the phone and then it worked just by kicking off a test run. But once you get to that point you will run into the issue the rest of us are having.

**Comment by xamiell** [comment]
@Moshex I'm facing the same problem on iOS UITests

> @IlyaBausovAkvelon iPhone iOS version 16 Xamarin.UITest is not able to enter text and this issue is still open on Xamarin.UITest version 4.0.1, I get the error of:
> 
> ```
> System.Exception : Error while performing ClearText(Marked("EmailEntry"))
>   ----> System.TimeoutException : Timed out waiting for keyboard.
> ```

**Comment by xamiell** [comment]
Update: Testing on some iOS simulator I can see that Calabash only fails on iPhone SE but on iPhone 11 the keyboard works as expected.

Source of help: https://discuss.bitrise.io/t/xamarin-ios-uitest-step-breaks-when-entering-text/1657

> @Moshex I'm facing the same problem on iOS UITests.
> 
> I was reading the documentation to use the Soft Keyboard https://learn.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/entering-text#Disable_the_Hardware_Keyboard but still happening.
> 
> > @IlyaBausovAkvelon iPhone iOS version 16 Xamarin.UITest is not able to enter text and this issue is still open on Xamarin.UITest version 4.0.1, I get the error of:
> > ```
> > System.Exception : Error while performing ClearText(Marked("EmailEntry"))
> >   ----> System.TimeoutException : Timed out waiting for keyboard.
> > ```

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon 
I see there is a Xamarin.UITest 14.1.0, unfortunately this fails to install ios apps on simulators in macOS-12 build hosts in Azure DevOps. Manually installing the .app into iOS 16 simulators via cli gets further, but .StartApp() throws with 'failed to start DeviceAgent', and not sure we can work around that one.

Any suggestions?

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev, thank you for reporting this issue. Which simulator version is being used? 16.0 or 16.2?
Also could you provide more details about how you tried to manually install the DeviceAgent app?

**Comment by JohnHDev** [comment]
> @JohnHDev, thank you for reporting this issue. Which simulator version is being used? 16.0 or 16.2?
> Also could you provide more details about how you tried to manually install the DeviceAgent app?

@IlyaBausovAkvelon it appears the macOS-12 build host is using iOS 16.2 simulators.

I haven't tried to manually install DeviceAgent, I had to manually install the app Im testing though:
````xcrun simctl install {simulator.Id} {appName}.app

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev could you try to use 16.0 simulators?

**Comment by JohnHDev** [comment]
> @JohnHDev could you try to use 16.0 simulators?

I can try, the macOS-12 build hosts are predefined but I might be able to force install the 16.0 sims. Will report back later today.

**Comment by Moshex** [comment]
I tried to run Xamarin.UITest version 4.1.0 on a physical device with OS version 16.2.0  and I get the following error:
```
7 - UnsuccessfulXamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent

ExitCode: 70

    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/DeviceAgent.iOS.Dependencies/97c6e23b5f002a1312c71a751de5262f/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun -destination id=00008110-000C24C93A82401E -derivedDataPath /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/logs/2023.01.26.080929/DerivedData
    IDEDerivedDataPathOverride = /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/logs/2023.01.26.080929/DerivedData
    IDEPackageSupportUseBuiltinSCM = YES
		{ id:00008110-000C24C93A82401E }
		{ platform:iOS Simulator, id:009AAEBB-F5DB-43E8-A6E5-D301823C91F5, OS:12.4, name:iPad Air }
		{ platform:iOS Simulator, id:06F0BEB7-5606-463F-A511-4AF55488FBB3, OS:14.2, name:iPad Air (4th generation) }
		{ platform:iOS Simulator, id:0AF32C35-34C5-458D-9DFB-F6B5BCC54146, OS:13.1, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:0E34C95B-026D-44A5-9127-9FE66FA1AE81, OS:13.7, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:0E7F0724-EFE7-48B9-BA78-4FC2303CEAEA, OS:13.1, name:iPhone 8 }
		{ platform:iOS Simulator, id:0EB28AC0-A9F9-4CE7-80EB-4D282178BA06, OS:12.4, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:103B6792-2EE5-45F1-918B-9E92A2F8C31A, OS:13.7, name:iPad Air (3rd generation) }
		{ platform:iOS Simulator, id:12D5A411-B86E-4E45-A826-96CC73495375, OS:14.1, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:136605F4-0EA5-4305-9FDF-C403A0EDBE53, OS:12.4, name:iPad Pro (12.9-inch) (1st generation) }
		{ platform:iOS Simulator, id:15B984FA-8AF6-485E-A05C-3B6CEE841FBB, OS:13.1, name:iPad Air (3rd generation) }
		{ platform:iOS Simulator, id:15BCF152-727B-47C5-A6CA-355FDA188B22, OS:14.2, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:16AEA1B2-B266-4C5D-998E-209230F373F9, OS:14.5, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:16B2DF7C-09E8-4551-88E8-390495AEFF59, OS:14.5, name:iPhone 8 }
		{ platform:iOS Simulator, id:171B4C7A-4CBD-4775-9D45-F95F6C9D93E2, OS:12.4, name:iPhone Xs Max }
		{ platform:iOS Simulator, id:1C893C5E-9E16-4CDF-A7AF-24C95C01F064, OS:14.4, name:iPad (8th generation) }
		{ platform:iOS Simulator, id:1E4C13A4-F0A8-45B4-877D-A4E5460A8A38, OS:14.5, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:250E126E-746E-47BD-A0A7-B362379A8EFB, OS:14.2, name:iPhone 12 Pro Max }
		{ platform:iOS Simulator, id:28E86157-AA4E-404B-A859-D769DB0F5709, OS:16.2, name:iPhone SE (3rd generation) }
		{ platform:iOS Simulator, id:29098826-B0C8-468E-949C-2E2C8A4B0249, OS:14.0.1, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:29600F9F-B17F-4700-9554-E3E6AC3BF9E6, OS:16.2, name:iPad mini (6th generation) }
		{ platform:iOS Simulator, id:2B470687-E7F4-4A75-A24B-153CFE7F05EB, OS:14.1, name:iPhone 8 }
		{ platform:iOS Simulator, id:2CE95DE8-3CE3-47B3-B47F-DED8BFEC6BAE, OS:14.5, name:iPad Air (4th generation) }
		{ platform:iOS Simulator, id:2D74EA8D-2C7C-4077-A179-7B6FE9A8D156, OS:13.7, name:iPhone 8 }
		{ platform:iOS Simulator, id:2E123F65-AA02-4C4A-AED3-217A82DE1DF8, OS:14.1, name:iPad Pro (11-inch) (2nd generation) }
		{ platform:iOS Simulator, id:31324968-F2B2-453F-BFBD-FBD9BB2D261E, OS:14.2, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:334A780B-ECAF-4DF8-921C-2EF8C03B71A1, OS:12.4, name:iPhone 6 }
		{ platform:iOS Simulator, id:3470E166-F1EF-49BE-A9F1-91D96E4765D5, OS:13.7, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:36E4C641-2B70-49ED-AE38-63E108A47C7C, OS:12.4, name:iPhone 8 }
		{ platform:iOS Simulator, id:3711BE9D-F2F3-4CF7-ADC5-FFD269F6FA19, OS:14.2, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:387608B4-7899-4C2C-B8D8-1DB8D8B9BA34, OS:13.2.2, name:iPad (7th generation) }
		{ platform:iOS Simulator, id:3A3F65E7-3283-44E1-9821-34449522423A, OS:16.2, name:iPhone 14 Pro Max }
		{ platform:iOS Simulator, id:3DB86963-7DAB-4226-A455-C85E918F6AB3, OS:14.1, name:iPad Air (4th generation) }
		{ platform:iOS Simulator, id:41B3D4EF-438F-4CA6-85C3-DD95A4712DF7, OS:14.3, name:iPhone 12 mini }
		{ platform:iOS Simulator, id:41F8810A-FD39-4531-9DDB-43C789749F16, OS:16.2, name:iPad (10th generation) }
		{ platform:iOS Simulator, id:422A4D46-E079-4140-93CE-11065E9CBF5E, OS:12.4, name:iPhone SE (1st generation) }
		{ platform:iOS Simulator, id:428333A8-D0DF-4376-AD6B-41B0B49EC4E3, OS:12.4, name:iPad Pro (11-inch) (1st generation) }
		{ platform:iOS Simulator, id:433C69A1-DF2F-4649-84A1-3F1F8ABD2982, OS:12.4, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:43EA680C-ED3C-449F-A96A-97735122BA09, OS:13.2.2, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:44D44C71-AF80-498D-B76C-2F8991F55409, OS:14.0.1, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:485713D1-C852-42C4-B5B7-D249258DE827, OS:14.0.1, name:iPhone 11 }
		{ platform:iOS Simulator, id:48F09F74-2D60-402E-9404-95EF3169F31C, OS:14.1, name:iPhone 12 Pro }
		{ platform:iOS Simulator, id:491D48DF-FDC1-49B3-B556-EA73CBD68D40, OS:14.5, name:iPad Pro (12.9-inch) (5th generation) }
		{ platform:iOS Simulator, id:4ADF9872-8237-4437-893D-FC0BC6DCA8B2, OS:14.1, name:iPad (8th generation) }
		{ platform:iOS Simulator, id:4DEB1A4A-C3D1-427B-A318-C9D21FB49793, OS:14.5, name:iPad (8th generation) }
		{ platform:iOS Simulator, id:4E35271B-AD20-43EE-AF4E-FD7D5AE7B2CF, OS:14.3, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:4F989D66-CCAE-4379-A9D9-9483F62D5CE8, OS:13.0, name:iPad Air (3rd generation) }
		{ platform:iOS Simulator, id:535E8CBF-C619-4B5A-AB04-53A74DFFF0BA, OS:14.3, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:5435267F-27C9-43F6-82E0-69251486CC01, OS:14.2, name:iPhone 12 mini }
		{ platform:iOS Simulator, id:55C6AE48-7FC8-4A6C-A477-563F1FC85529, OS:14.2, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:5686F035-6BA3-4248-99B7-91411B36419C, OS:13.2.2, name:iPhone 11 }
		{ platform:iOS Simulator, id:57F389AF-2F9A-48B5-8D9B-9849B8EEBE09, OS:14.2, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:584A0F1E-2C57-4C96-B4E8-71A27F4296EA, OS:14.3, name:iPhone 11 }
		{ platform:iOS Simulator, id:5862E763-34E9-42B1-A0B9-7E4762C8A90C, OS:13.1, name:iPad Pro (11-inch) (1st generation) }
		{ platform:iOS Simulator, id:5A047128-CED9-416B-B4C7-494EB42B8539, OS:14.4, name:iPhone 8 }
		{ platform:iOS Simulator, id:5D73BFF4-3030-4178-8F2C-CBE338DD611E, OS:14.3, name:iPhone 12 }
		{ platform:iOS Simulator, id:5E313D59-9755-4DA4-BF92-BE36492FF586, OS:13.1, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:5EB914A7-EC8C-4E96-B261-150A43B6E03C, OS:13.2.2, name:iPad Air (3rd generation) }
		{ platform:iOS Simulator, id:5F127D8B-33BA-45C5-8F49-84F19A75EEC1, OS:13.7, name:iPhone 11 }
		{ platform:iOS Simulator, id:5FD41E67-AD19-49B2-94AC-0E49BFE223CE, OS:14.5, name:iPad Pro (11-inch) (3rd generation) }
		{ platform:iOS Simulator, id:60DECCD1-73C9-4246-B6C6-C99197C34C9C, OS:14.0.1, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:6191F1FD-1F39-4B58-AB5C-69FF9940D694, OS:12.4, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:6227C8F3-30DC-4035-AD1C-24F20DF3BB65, OS:12.4, name:iPad (5th generation) }
		{ platform:iOS Simulator, id:62F36EF3-C37C-405B-90CD-B783692F9A4F, OS:13.7, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:6412DC89-D541-49BA-A604-0468403A9F94, OS:14.3, name:iPad Air (4th generation) }
		{ platform:iOS Simulator, id:66D65DFD-886C-4156-99D8-DDFDE5A58BC6, OS:13.0, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:67F5A897-3471-4D15-8A13-ED9793109680, OS:14.0.1, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:6BCC5E85-879C-41DA-BC15-8BF77B54C4E9, OS:14.2, name:iPhone 8 }
		{ platform:iOS Simulator, id:6DE83959-1E79-4D30-8DEC-2153195861D0, OS:16.2, name:iPhone 14 }
		{ platform:iOS Simulator, id:6EEBAC39-663F-427E-8475-AEE732DA93D4, OS:14.3, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:6FA53DB1-E974-4845-AB2A-2AAE464D027C, OS:12.4, name:iPad Pro (12.9-inch) (3rd generation) }
		{ platform:iOS Simulator, id:6FB80E7B-64D6-4D2A-8D27-29CE89D5F27E, OS:13.2.2, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:70EEEF42-D9D2-42B4-AC2C-2DF40ACB9308, OS:14.3, name:iPad (8th generation) }
		{ platform:iOS Simulator, id:72301711-27C3-4865-AAAB-CA4441863C71, OS:14.5, name:iPhone 11 }
		{ platform:iOS Simulator, id:7444DE44-A5FE-4CCB-9125-EFE65AB4DEE5, OS:14.4, name:iPad Pro (11-inch) (2nd generation) }
		{ platform:iOS Simulator, id:747B91BE-5EF8-4FEB-88B1-E826FC5227D1, OS:14.4, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:772E7CDF-52CB-4865-B441-7567DFDB290B, OS:14.5, name:iPod touch (7th generation) }
		{ platform:iOS Simulator, id:773294AB-3854-483A-B582-CDF77B3E8074, OS:14.5, name:iPhone 12 mini }
		{ platform:iOS Simulator, id:792CA0DC-6906-4CC9-A253-04449BBDAC77, OS:13.7, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:798503A3-49BA-4402-8094-8AFC4218A3C3, OS:14.3, name:iPhone 12 Pro }
		{ platform:iOS Simulator, id:799FB671-8650-4EAE-B9B9-78F4F3884499, OS:14.0.1, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:7BFD7AA8-DE73-427D-A1FF-7CE5DB6E0E46, OS:13.1, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:7D1B615D-664F-4A55-B418-185AF703BEC3, OS:14.1, name:iPhone 11 }
		{ platform:iOS Simulator, id:8090AA39-9E8E-4D98-BCDE-2E41C0DBF48F, OS:13.0, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:843B683D-1981-4E48-859D-B22150D9CBE8, OS:12.4, name:iPhone 6s }
		{ platform:iOS Simulator, id:84BB2F78-F1C7-4927-8DA7-D15F7CBE858D, OS:14.4, name:iPhone 12 Pro }
		{ platform:iOS Simulator, id:85AE591D-0DA8-4472-99FB-CFEFB00A71C6, OS:13.0, name:iPad Pro (11-inch) (1st generation) }
		{ platform:iOS Simulator, id:85B4E966-E8B3-46CC-AF26-3665A4B9B081, OS:12.4, name:iPad Air (3rd generation) }
		{ platform:iOS Simulator, id:86CB414A-ED67-42E0-8DAC-8EDCB4FCF9F1, OS:14.4, name:iPhone 12 mini }
		{ platform:iOS Simulator, id:86EDD795-BA3F-48AD-8769-981E5C5A36AB, OS:13.0, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:8798B00B-23C8-4F07-98B2-EEAD5C35E024, OS:14.1, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:89E1F5F8-FC13-47B0-857A-BAA5DD783E16, OS:14.5, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:8A6E2044-D5BD-43AC-AA68-80596BE45BE0, OS:12.4, name:iPhone X?? }
		{ platform:iOS Simulator, id:8E38A279-2347-49E0-9BFC-2144B95634CD, OS:12.4, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:8E491678-E3C1-4C5B-A87C-F22041D47EB9, OS:14.4, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:9081C51B-31A7-4C80-AA99-47BD8957F271, OS:13.1, name:iPhone 11 }
		{ platform:iOS Simulator, id:914A03EF-BA25-4F83-A068-BF7E1AC46410, OS:14.1, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:9162E18C-2B7C-4F5B-9469-ED9CF92338DF, OS:14.4, name:iPhone 12 }
		{ platform:iOS Simulator, id:93A3434C-4F75-4D87-90E9-CC58746C0E56, OS:14.2, name:iPhone 12 }
		{ platform:iOS Simulator, id:948971C2-17DD-4B01-994B-614DF05ED2CF, OS:13.1, name:iPad Pro (12.9-inch) (3rd generation) }
		{ platform:iOS Simulator, id:96939910-2B74-4394-A022-779B030EF93C, OS:14.0.1, name:iPod touch (7th generation) }
		{ platform:iOS Simulator, id:97471041-3108-4FD9-A7F9-4E85B085DF7A, OS:13.7, name:iPad Pro (11-inch) (2nd generation) }
		{ platform:iOS Simulator, id:996AE299-D8BA-4F1D-BF15-29EF77A3535C, OS:12.4, name:iPhone Xs }
		{ platform:iOS Simulator, id:9A7F9834-A6CE-4B42-A16B-4FF128151AEB, OS:12.4, name:iPhone X }
		{ platform:iOS Simulator, id:9C6FDCE5-CB0B-4BD5-AA82-C389474FD135, OS:14.1, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:A1097DF0-2481-4111-98BE-1A7C4E76E21C, OS:12.4, name:iPad (6th generation) }
		{ platform:iOS Simulator, id:A1FB0E2E-1788-491A-BCCC-35AD436086EA, OS:13.7, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:A2587649-FECC-4D7E-A63A-014E4F75C608, OS:13.2.2, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:A32AD90C-6583-4392-A58C-2C01050F64EF, OS:13.0, name:iPhone 8 }
		{ platform:iOS Simulator, id:A46B8838-933B-404E-A7AA-8BB463B2A433, OS:13.1, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:A4778198-6D46-4DA3-8658-1F2B9A17C260, OS:13.2.2, name:iPhone 8 }
		{ platform:iOS Simulator, id:A5A91309-6F04-4714-9441-117F1F473818, OS:12.4, name:iPhone 5s }
		{ platform:iOS Simulator, id:A87D764A-214E-44CA-81EE-4C8AB7457521, OS:16.2, name:iPhone 14 Pro }
		{ platform:iOS Simulator, id:AA1D27F8-1D03-49FE-BCEE-0DF05121330D, OS:14.1, name:iPod touch (7th generation) }
		{ platform:iOS Simulator, id:AE6EC00D-36AF-4615-9405-7C9C24247FDB, OS:14.3, name:iPhone 12 Pro Max }
		{ platform:iOS Simulator, id:B0711E82-486A-4ADD-8F2E-F803C9165910, OS:14.1, name:iPhone 12 Pro Max }
		{ platform:iOS Simulator, id:B17B9CDB-D7E9-41A8-A2F3-4EB8ED6683CD, OS:14.1, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:B1F1137A-F43A-4406-9759-F1F303FB2EBC, OS:14.2, name:iPhone 11 }
		{ platform:iOS Simulator, id:B3523F72-0A43-469C-A5B0-940875E5F55A, OS:14.4, name:iPhone 12 Pro Max }
		{ platform:iOS Simulator, id:B3B809DF-8E32-49BC-8F86-74853854A581, OS:12.4, name:iPad Air 2 }
		{ platform:iOS Simulator, id:B41916CB-935E-4606-AC60-12C070F40321, OS:16.2, name:iPad Air (5th generation) }
		{ platform:iOS Simulator, id:B6B39033-9117-479C-A48D-7C23E219EAB2, OS:14.5, name:iPhone 12 }
		{ platform:iOS Simulator, id:B915944E-CAB3-4D1C-8AFE-5E98E7FDC034, OS:14.3, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:BECDFFC0-1E5F-4E0A-B768-96220C9338AB, OS:14.3, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:BFD6CB13-FD38-41BC-A01F-1AA5E19B6844, OS:14.4, name:iPad Air (4th generation) }
		{ platform:iOS Simulator, id:C0A7F506-DECC-465C-9596-DA03FBAC249F, OS:13.7, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:C0A8E6C0-E6CE-4D0A-857E-C16184F78E5D, OS:14.2, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:C39509DC-78D3-42B8-B57A-1C65103BEB7A, OS:13.0, name:iPhone 11 }
		{ platform:iOS Simulator, id:C4130F77-EE16-4298-8A7D-35E92F91159D, OS:14.1, name:iPhone 12 mini }
		{ platform:iOS Simulator, id:C4A871B0-8072-4069-8FA4-89D0EBB1CE8D, OS:13.0, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:C4AAE097-7937-4029-A355-04217F94021A, OS:14.4, name:iPhone 11 }
		{ platform:iOS Simulator, id:C608BA62-D96B-44FF-860A-A7C6AB828166, OS:13.2.2, name:iPad Pro (11-inch) (1st generation) }
		{ platform:iOS Simulator, id:C8B7C513-A512-4B31-820A-77FD817C6F3B, OS:14.2, name:iPod touch (7th generation) }
		{ platform:iOS Simulator, id:CA5BC44A-0538-4FD6-BD46-8A73B4D45E12, OS:14.3, name:iPod touch (7th generation) }
		{ platform:iOS Simulator, id:CB8495CD-3422-4572-B2EF-96C1A6E7A5F3, OS:14.5, name:iPhone 12 Pro Max }
		{ platform:iOS Simulator, id:CCD040DB-8001-45BA-9624-7414B95C62C7, OS:14.2, name:iPad Pro (11-inch) (2nd generation) }
		{ platform:iOS Simulator, id:CCD1095C-67A2-4C7A-92AD-AD6194AA3DBE, OS:13.7, name:iPad (7th generation) }
		{ platform:iOS Simulator, id:CCD953FC-32C0-4725-B0D4-D039DCE9E654, OS:14.4, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:CDAC60AA-5DBC-4B60-815F-6162A6B670B8, OS:14.3, name:iPad Pro (11-inch) (2nd generation) }
		{ platform:iOS Simulator, id:CE63245B-1EB0-4207-B8C3-87E559843364, OS:14.4, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:CF79024A-BDA0-474D-AF09-1AFAA11C286F, OS:12.4, name:iPad Pro (10.5-inch) }
		{ platform:iOS Simulator, id:D140BD56-045D-452C-8189-0E5CB7222F97, OS:14.0.1, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:D520EEA8-B558-4F71-9E18-3F225B7EED94, OS:14.5, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:DC263003-0993-4464-85B8-3C78ADDA62E6, OS:14.4, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:DEDD3F07-F4EF-44D3-9E0F-E86C3B3301AD, OS:12.4, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
		{ platform:iOS Simulator, id:E0F21B78-A318-4717-81A9-1C8B129B78EF, OS:14.4, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:E11E8CFE-5EBF-49C4-813F-2635A778E68C, OS:12.4, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:E5062D68-580F-4B63-8E65-EBB7AA2A38B9, OS:13.2.2, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:E942A3BF-4B54-4E02-95C8-89C983DB5345, OS:14.0.1, name:iPad Pro (11-inch) (2nd generation) }
		{ platform:iOS Simulator, id:EAFDA806-8D03-426F-95CA-229213BC70DE, OS:14.3, name:iPhone 8 }
		{ platform:iOS Simulator, id:EC947F67-4DE1-4AA7-84C2-5DEFE3A3638D, OS:14.0.1, name:iPad (8th generation) }
		{ platform:iOS Simulator, id:ED6A3553-9FEE-4E30-8AF0-C29508B50D9C, OS:14.1, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:EF0B5EF7-A8BF-4918-A652-726087489827, OS:13.2.2, name:iPad Pro (12.9-inch) (3rd generation) }
		{ platform:iOS Simulator, id:EFB09D3C-5BB8-4CD7-8F18-75C1C6C46433, OS:16.2, name:iPhone 14 Plus }
		{ platform:iOS Simulator, id:EFF0D6CE-BD31-4FAE-AB7D-35BCEB209FA5, OS:14.5, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:F1861F3D-01E2-4479-9092-E151FAF8A518, OS:14.5, name:iPhone 12 Pro }
		{ platform:iOS Simulator, id:F1E7DBF9-1111-4B6C-92C0-00244E4106ED, OS:14.3, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:F31D8801-E342-4AB1-BBBA-2DA7FFA173C3, OS:14.0.1, name:iPad Air (4th generation) }
		{ platform:iOS Simulator, id:F32688BD-B6A7-4EFE-ADC1-D081799B1BA5, OS:14.1, name:iPhone 12 }
		{ platform:iOS Simulator, id:F39FB253-D502-4232-A77E-35E48483233C, OS:14.2, name:iPhone 12 Pro }
		{ platform:iOS Simulator, id:F546E2A0-9AD4-40A3-9B3C-02DE2B26BEAE, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
		{ platform:iOS Simulator, id:F940D3D4-7CCC-4C14-BABD-500216C4B030, OS:14.2, name:iPad (8th generation) }
		{ platform:iOS Simulator, id:FA0A5B63-0178-46CF-A379-4340848CD78B, OS:13.0, name:iPad Pro (12.9-inch) (3rd generation) }
		{ platform:iOS Simulator, id:FB920232-A74A-455D-8C3C-20143F342408, OS:14.0.1, name:iPhone 8 }
		{ platform:iOS Simulator, id:FC7F09EA-68B4-47D7-A64E-8B0AC1C0D4D7, OS:12.4, name:iPhone 7 }
		{ platform:iOS Simulator, id:FD476DFC-7AD8-480B-84EF-43FA085C0E5E, OS:14.4, name:iPod touch (7th generation) }
		{ platform:iOS Simulator, id:FE2C1539-A925-4D93-AE70-89B8D3029EBE, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
		{ platform:iOS, id:00008110-000C24C93A82401E, name:Moshe???s iPhone (2), error:Device is busy (Fetching debug symbols for Moshe???s iPhone (2), Making Moshe???s iPhone (2) ready for development) }
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:macOS, arch:x86_64, id:7CF605ED-6290-5F52-BB01-F2603E5BB543 }
		{ platform:macOS, arch:x86_64, variant:DriverKit, id:7CF605ED-6290-5F52-BB01-F2603E5BB543 }
		{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:7CF605ED-6290-5F52-BB01-F2603E5BB543 }
		{ platform:macOS, arch:x86_64h, id:7CF605ED-6290-5F52-BB01-F2603E5BB543 }
		{ platform:macOS, arch:x86_64h, variant:DriverKit, id:7CF605ED-6290-5F52-BB01-F2603E5BB543 }
		{ platform:macOS, arch:x86_64h, variant:Mac Catalyst, id:7CF605ED-6290-5F52-BB01-F2603E5BB543 }
		{ platform:macOS, name:Any Mac }
		{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Any watchOS Simulator Device }
		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
	Available destinations for the "Transient Testing" scheme:
	Ineligible destinations for the "Transient Testing" scheme:
	The requested device could not be found because no available devices matched the request.
2023-01-26 08:10:01.022 xcodebuild[31026:1735305] Writing error result bundle to /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/ResultBundle_2023-26-01_08-10-0001.xcresult
Command line invocation:
User defaults from command line:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
Result message:
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent

ExitCode: 70
```

**Comment by Moshex** [comment]
@IlyaBausovAkvelon When you say some times how did you get it to work?

**Comment by IlyaBausovAkvelon** [comment]
I need to debug it a little deeper to say when it's working and when it's not.

**Comment by IlyaBausovAkvelon** [comment]
@Moshex I see that your device is having busy state:

`{ platform:iOS, id:00008110-000C24C93A82401E, name:Moshe???s iPhone (2), error:Device is busy (Fetching debug symbols for Moshe???s iPhone (2), Making Moshe???s iPhone (2) ready for development) }`

The xcodebuild process having problems to run. It's not a Xamarin.UITest issue.

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev Could you provide error log for running Xamarin.UITest on simulator?

**Comment by Moshex** [comment]
> @Moshex I see that your device is having busy state:
> 
> `{ platform:iOS, id:00008110-000C24C93A82401E, name:Moshe???s iPhone (2), error:Device is busy (Fetching debug symbols for Moshe???s iPhone (2), Making Moshe???s iPhone (2) ready for development) }`
> 
> The xcodebuild process having problems to run. It's not a Xamarin.UITest issue.

What does that mean what do I need to do to fix that?

**Comment by IlyaBausovAkvelon** [comment]
@Moshex Try reconnecting and rebooting device. Also can you see your device in Xcode -> Window -> Devices and Simulators?

**Comment by Moshex** [comment]
@IlyaBausovAkvelon I was able to get it to work thank you for your help, I feel like this issue is close as soon as we can get App center to run with the latest version of [Xamarin.UITest]

**Comment by IlyaBausovAkvelon** [comment]
@Moshex, we are working on it.

**Comment by JohnHDev** [comment]
> @JohnHDev Could you provide error log for running Xamarin.UITest on simulator?

@IlyaBausovAkvelon 
Here is the log running on macos12 build host in Azure DevOps. As you can see if appears to think the simulator is already booted, when it isn't.


20:34:24,286 I  16 .ctor() OsVersion 16.2
20:34:24,286 I  16 .ctor() Language en-GB
20:34:27,620 I  16 Shutdown() 6112C973-C397-4EAF-8973-705608B6C6F7
20:34:27,886 I  10 Run() EDR: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
20:34:27,897 I  10 Run() EDR: Unable to shutdown device in current state: Shutdown
20:34:27,907 I  16 StartiOSApp() Starting simulator iPhone 14 Pro Max iOS 16.2...
20:40:39,670 E  16 StartiOSApp() Failed to install app /Users/runner/work/1/s/AppDev.Maui.Playground/AppDev.XF/AppDev.XF.iOS/bin/iPhoneSimulator/Debug/AppDev.XF.iOS.app

ExitCode: 134
	0   CoreFoundation                      0x00007ff81c293e9b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff81bff5e48 objc_exception_throw + 48
	10  dyld                                0x000000010f0a752e start + 462
	2   iOSDeviceManager                    0x000000010cb40430 +[Command resourcesFromArgs:] + 0
	3   iOSDeviceManager                    0x000000010cb39ecc +[Codesigner adHocSign:resourcesToInject:] + 487
	4   iOSDeviceManager                    0x000000010cb39843 +[Codesigner resignApplication:withProvisioningProfile:withCodesignIdentity:resourcesToInject:] + 149
	5   iOSDeviceManager                    0x000000010cb4606e -[Simulator installApp:mobileProfile:codesignIdentity:resourcesToInject:forceReinstall:] + 333
	6   iOSDeviceManager                    0x000000010cb46501 -[Simulator installApp:resourcesToInject:forceReinstall:] + 33
	7   iOSDeviceManager                    0x000000010cb37ee6 +[InstallAppCommand execute:] + 868
	8   iOSDeviceManager                    0x000000010cb432c7 +[CLI process:] + 1114
	9   iOSDeviceManager                    0x000000010cb2da35 main + 121
(
)
*** First throw call stack:
2023-02-09 20:40:19.139 iOSDeviceManager[8208:30201] *** Terminating app due to uncaught exception 'CBXException', reason: 'Error codesigning /Users/runner/work/1/s/AppDev.Maui.Playground/AppDev.XF/AppDev.XF.iOS/bin/iPhoneSimulator/Debug/AppDev.XF.iOS.app: '
App com.redacted.AppDev-XF is not installed on 6112C973-C397-4EAF-8973-705608B6C6F7
libc++abi: terminating with uncaught exception of type NSException
Simulator is already booted.
20:40:39,693 E  16 StartiOSApp()   at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Http.HttpClient httpClient, System.Boolean clearAppData) [0x001e3] in <09eb939889804029b9f05a6dbb1953f7>:0 
  at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Http.HttpClient httpClient, Xamarin.UITest.TestCloud.TestCloudiOSAppConfiguration testCloudAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient testCloudWsClient, Xamarin.UITest.Shared.Http.HttpClient xtcServicesClient, System.Boolean testCloudUseDeviceAgent) [0x00065] in <09eb939889804029b9f05a6dbb1953f7>:0 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Execution.IExecutor executor) [0x0026f] in <09eb939889804029b9f05a6dbb1953f7>:0 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration) [0x00000] in <09eb939889804029b9f05a6dbb1953f7>:0 
  at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp (Xamarin.UITest.Configuration.AppDataMode appDataMode) [0x00017] in <09eb939889804029b9f05a6dbb1953f7>:0 
  at AppDev.XF.UITests.AppManager.StartiOSApp (AppDev.XF.UITests.Simulator simulator, System.String language, System.String appFile) [0x00069] in <119d820a733b4b3d829dafcd6bdb8268>:0

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev Thank you for the log. I'll check it.

**Comment by JohnHDev** [comment]
> @JohnHDev Thank you for the log. I'll check it.

@IlyaBausovAkvelon let me know if you want me to try something else.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon if it helps, installing iOS 12.4 and 15.2 simulators on the MacOS 12 build host works and I can run tests against those, but I can't run tests against iOS 16.2 simulators, they all fail with the above ExitCode: 134 error.

Very frustrating that we can't run tests against the latest iPhone simulators. We currently run 10 concurrent build hosts in Azure DevOps on private repositories, and we are only looking to increase that as our workload increases. It becomes increasingly difficult to justify the costs when we still can't run tests against iOS 16. We really need a solution here.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon ok I have managed to work around the issue after a lot of trial and error with booting the sim via CLI, installing via CLI, launching via CLI (none of which helped actually). My workaround means I can now run iOS 16 simulators on macos12 build hosts, but it takes **16 minutes** to get successfully .StartApp(), where as an iOS 15 simulator on macos12 takes 2 minutes to .StartApp().

This is a workaround only, not a long term solution. But at least, right now, Im not blocked. We do need a long term solution.

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev, thank you for the information provided. We will try to resolve this issue.

**Comment by JohnHDev** [comment]
@IlyaBausovAkvelon are there any release notes we can look at for 4.1.1? Im not seeing any improvements for iOS 16 on macOS-12 build hosts, but would be good to see what other improvements have been made.

Thanks
John

**Comment by IlyaBausovAkvelon** [comment]
@JohnHDev it's in the Release Notes tab of NuGet package page.
<img width="786" alt="Screenshot 2023-02-20 at 10 55 20 AM" src="https://user-images.githubusercontent.com/69856845/220072647-2f366ebb-1cf3-4d0e-93d6-e8a0012dfe26.png">

**Comment by ericlobner** [comment]
The new version of Xamarin.UITest resolved some of our issues.

https://www.nuget.org/packages/Xamarin.UITest/4.1.2#release-body-tab

**Comment by Mokshi99** [comment]
@ericlobner keyboard is not opening and entering text is not working in Simulator with Xcode 14, even the updated versions of Xamarin.UITest are unable to resolve the issue.
any update on this issue.

Thanks
Mokshi

**Comment by ericlobner** [comment]
It looks like a new version of Xamarin.UITest, 4.1.3, was just released, possibly try that, or maybe revert back to 4.1.2 which is what I was using.

**Comment by jeromelaban** [comment]
I'm also randomly getting this particular error, when running locally or on a local run in azure hosted agents. It's not clear what makes it happen, and stopping the simulator before hand does not seem to have an effect. 

I tested with 4.1.3 and below, it only happens with 14.1 simulators and higher.

```
*** First throw call stack:
2023-05-01 13:28:31.824 iOSDeviceManager[27838:81322] *** Terminating app due to uncaught exception 'CBXException', reason: 'Error codesigning /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xdb/DeviceAgent.iOS.Dependencies/1ef377d9309b398b647336be30dbc164/app/DeviceAgent-Runner.app: '
App sh.calaba.DeviceAgent.xctrunner is not installed on CFB94DA7-6506-4AE0-A5E9-4B01585F5CAF
libc++abi: terminating with uncaught exception of type NSException
Simulator is already booted.
  Stack Trace:
  Failed When_Polyline [1 ms]
  Error Message:
   OneTimeSetUp: System.TypeInitializationException : The type initializer for 'SamplesApp.UITests.SampleControlUITestBase' threw an exception.
  ----> Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to install DeviceAgent

ExitCode: 134
	0   CoreFoundation                      0x00007ff802b46e8b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff8028a4e48 objc_exception_throw + 48
	10  dyld                                0x0000000107c2152e start + 462
	2   iOSDeviceManager                    0x0000000100e08430 +[Command resourcesFromArgs:] + 0
	3   iOSDeviceManager                    0x0000000100e01ecc +[Codesigner adHocSign:resourcesToInject:] + 487
	4   iOSDeviceManager                    0x0000000100e01843 +[Codesigner resignApplication:withProvisioningProfile:withCodesignIdentity:resourcesToInject:] + 149
	5   iOSDeviceManager                    0x0000000100e0e06e -[Simulator installApp:mobileProfile:codesignIdentity:resourcesToInject:forceReinstall:] + 333
	6   iOSDeviceManager                    0x0000000100e0e501 -[Simulator installApp:resourcesToInject:forceReinstall:] + 33
	7   iOSDeviceManager                    0x0000000100dffee6 +[InstallAppCommand execute:] + 868
	8   iOSDeviceManager                    0x0000000100e0b2c7 +[CLI process:] + 1114
	9   iOSDeviceManager                    0x0000000100df5a35 main + 121
(
)
```

**Comment by Banley** [comment]
Will this issue be fixed in the next release iteration? If we can't get an estimated release date, any update would be helpful. Thank you.

**Comment by JohnHDev** [comment]
@Banley I worked around that issue by installing the .app file via the CLI:
`"xcrun", $"simctl install booted {appFile}"`
Haven't seen an issue since moving to this, all our Azure DevOps based UI tests have run successfully since making that change.

**Comment by Banley** [comment]
Thanks @JohnHDev I will give that a shot.

**Comment by christian26A** [comment]
Hi,

is anyone here able to work around this issue? Entertext is not working even using the latest UITest version.

**Comment by jeromelaban** [comment]
@JohnHDev after a bit of time, are you still finding your workaround to be stable? I'm also installing the app the same way, but I'm still getting the same "already booted" error once in a while.

**Comment by Moshex** [comment]
This issue can still not be tested due to this issue
https://github.com/microsoft/appcenter/issues/2536#issuecomment-1622390110

**Comment by IAmJoffa** [comment]
I've been playing around with this as we have the issue and really need it fixed. We can't do any testing on iOS as a result of starting with upgraded XCode and iPads. I have the DeviceAgent-Runner building and running from XCode but need to know where to put it so that it copies correctly.

Anyone have any ideas?

**Comment by jeromelaban** [comment]
This issue is indeed still very much present. I've had limited success with pre-installing the app as part of the testing, but there are days where the "Simulator is already booted" kicks in a lot, causing a lot of lost processing power.

**Comment by IAmJoffa** [comment]
I got this working by:

1. Downloading and building the Calabash Agent locally with the Development Certificates
2. Running it from XCode (Product -> Perform Action -> Test without Building), when you do this it will prompt you for Authorisation when running to Enable the Automation Testing in iOS
3. I built my Application in Debug Mode with the Calabash code included in it and deployed it
4. Manually starting the Application
5. Run the Automation Tests from Visual Studio using ConnectApp() and not StartApp() function

Yep it a manual PITA but it works and allows us to test the App under iOS. I had to code up my tests to reset the App on each start or having it return to the same place as it started for each test to make running the tests easier.

**Comment by IAmJoffa** [comment]
You can get the Calabash Device Agent for iOS here: https://github.com/calabash/DeviceAgent.iOS

Then I changed the config to "Automatically Manage Signing" selected a Team from the Provisioning Profile and changed the Bundle Name to "com.<myCompany>.test.AppStub"

**Comment by IAmJoffa** [comment]
Question for @IlyaBausovAkvelon and the folks who maintain UITest is it possibly to get a version of the Xamarin.UITest library that has a flag to stop it trying to load and install the Calabash.iOS Agent when we call StartApp()? vs ConnectoToApp()

The reason I ask is because I have the Agent running locally and am using UITest 4.3.0 to get the iOS List Picker fix but the List picker function requires the app to have been started by the Device Agent to get the reference to the currentApplication (I've debugged this). If I start our App manually or through the debugger then it is not started by the DeviceAgent and this flag is not set in the Calabash Agent and the list picker function does not work.

Or is there some progress in getting the DeviceAgent to load automatically? The only way I can get it to run is through the XCode debugger, otherwise it crashes on start even if I build and deploy to myself.

**Comment by IAmJoffa** [comment]
An alternative would be to call the Calabash DeviceAgent http /session endpoint and get the app started that way...

**Comment by Moshex** [comment]
@IAmJoffa  Are you saying that your strategy for the DeviceAgent does not work for version 4.3.0?

**Comment by IAmJoffa** [comment]
Hey @Moshex, Yeh it's not working only for List and Date/Time pickers due to the way that the Device Agent has to work with them. That's an XCUITest testing thing and how it's now implemented access to the pickers. XCUITest requires a loaded application and the way I'm doing it the Application is not loaded by the DeviceAgent and so can't access the pickers. I see a few possible options:

1. The good folks who do UITest provide the ability to not install the DeviceAgent when StartApp() is called so that we can run our own
2. The DeviceAgent has a HTTP Server in it and a call to the /session endpoint would load the Application being tested and provide the necessary internals so that the DeviceAgent can access the XCUITest Application object and control the pickers
3. Just get rid of the native iOS pickers from you App. The list one in particular is an abomination to use with more than 5 items. For the Date/Time pickers they are not much better for efficient data entry. I'm working on Enterprise Apps for workers on industrial sites and so the Native iOS pickers are not the best. I will most likely replace them with a custom control that also have a search feature.

**Comment by Moshex** [comment]
@IAmJoffa 
So what I gather is really we need the time to fix the ability to run Xamarin.UITest on a Physical device and there is not much of a workaround as of now?
@IlyaBausovAkvelon @DmitriyKirakosyan  
Is there any update on getting this issue fixed? it's really imperative for local testing to be able to run Xamarin.UITest on a Physical iOS device

Also as a side note for pickers, my team uses Syncfusion pickers for some functionality and I can tell you from experience that automating those pickers can be a pain. Per Syncfusion's website themselves, they state that they have limited control given to automation however I have found some ways around it that work but I am not a fan of it. 
her is the website for reference:

https://www.syncfusion.com/

**Comment by IAmJoffa** [comment]
@moshx yeh that's the case at the moment. We're not using SyncFusion for the drop down's but I will look at a custom control at some stage as this seems to be the easiest way to get things working. And we'd have to also replace the Date/Time pickers as well...

**Comment by IAmJoffa** [comment]
Hey Folks, does anyone know if the changes in the latest Xamarin.UiTest fixes this issue??? don't have my Mac with me today to test it but will try tomorrow...

https://www.nuget.org/packages/xamarin.uitest/#releasenotes-body-tab

**Comment by Moshex** [comment]
from my testing, I am still seeing an error on a physical device however the error has changed. This is the error on Xamarin.UITest Xamarin.UITest 4.3.1 :


```
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/DeviceAgent.iOS.Dependencies/e4733919efa6314bed5d3c97931b1820/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun -destination id=00008110-000C24C93A82401E -derivedDataPath /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/logs/2023.10.31.123746/DerivedData
    IDEDerivedDataPathOverride = /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/logs/2023.10.31.123746/DerivedData
    IDEPackageSupportUseBuiltinSCM = YES
	/var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/logs/2023.10.31.123746/DerivedData/Logs/Test/Test-Transient Testing-2023.10.31_12-37-47--0600.xcresult
	Runner (558) encountered an error (Failed to create a bundle instance representing '/private/var/containers/Bundle/Application/315CB54C-3106-4AFD-9D1D-5A411261BFC0/DeviceAgent-Runner.app/__TESTHOST__/PlugIns/DeviceAgent.xctest'. Check that the bundle exists on disk.)
** TEST EXECUTE FAILED **
*** If you believe this error represents a bug, please attach the result bundle at /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/logs/2023.10.31.123746/DerivedData/Logs/Test/Test-Transient Testing-2023.10.31_12-37-47--0600.xcresult
2023-10-31 12:37:48.357 xcodebuild[46155:1366882] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2023-10-31 12:37:48.357 xcodebuild[46155:1366882] [MT] IDETestOperationsObserverDebug: 0.537 elapsed -- Testing started completed.
2023-10-31 12:37:48.357 xcodebuild[46155:1366882] [MT] IDETestOperationsObserverDebug: 0.537 sec, +0.537 sec -- end
2023-10-31 12:37:48.527 DeviceAgent-Runner[558:30261] Running tests...
2023-10-31 12:37:48.537 DeviceAgent-Runner[558:30261] Failed to create a bundle instance representing '/private/var/containers/Bundle/Application/315CB54C-3106-4AFD-9D1D-5A411261BFC0/DeviceAgent-Runner.app/__TESTHOST__/PlugIns/DeviceAgent.xctest'. Check that the bundle exists on disk.
Command line invocation:
Test session results, code coverage, and logs:
Testing failed:
Testing started
User defaults from command line:
Result message:
System.AggregateException : One or more errors occurred. (Failed to launch DeviceAgent

ExitCode: 65
```

**Comment by DmitriyKirakosyan** [comment]
We're actively working on resolving this issue. Thank you for your understanding and patience!

**Comment by Moshex** [comment]
@DmitriyKirakosyan  
Thank you for the update!

**Comment by DmitriyKirakosyan** [comment]
@Moshex Meanwhile, I'm going to close this issue as a duplicate of https://github.com/microsoft/appcenter/issues/2536.
There are some other issues mentioned in this thread, but they are outdated.

**Comment by Moshex** [comment]
That's fine, fair enough.
