### ISSUE TITLE
Could not load file or assembly 'Xamarin.UITest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

### ISSUE THREAD

**Issue by JohnHDev** [microsoft/appcenter#2486]
Installed the latest Xamarin.UITest nugget, it has a missing dependency and so throws the above exception on StartApp.

**Comment by evgenyvalavin** [comment]
Same
.NET 7, Xamarin.UITest 4.0.0
```
Message: 
  System.TypeInitializationException : The type initializer for 'Xamarin.UITest.ConfigureApp' threw an exception.
      ----> System.IO.FileNotFoundException : Could not load file or assembly 'Xamarin.UITest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Stack Trace: 
    ConfigureApp.get_Android()
    AppManager.<StartApp>g__StartAndroidApp|10_1() line 35
   ...
```

**Comment by MrAusnadian** [comment]
Having this same issue with Xamarin.UITest nuget package version 4.0.0 ()https://www.nuget.org/packages/Xamarin.UITest/4.0.0)

**Comment by LeBuzzy** [comment]
Same here, downgraded to 3.2.9, and it works !

**Comment by JohnHDev** [comment]
I have been told by support that a fix is due the end of this week.

**Comment by Banley** [comment]
> I have been told by support that a fix is due the end of this week.

End of THIS week, I take it?

**Comment by JohnHDev** [comment]
I have chased, they no longer have an ETA.

**Comment by MrAusnadian** [comment]
Looks like it might be fixed in https://www.nuget.org/packages/Xamarin.UITest/4.0.1#release-body-tab

**Comment by Moshex** [comment]
just tested it, and it is fixed in Xamarin.UITest; version 40.1

**Comment by JohnHDev** [comment]
@Moshex Its a shame it doesn't actually fix the iOS 16 issues.

**Comment by Moshex** [comment]
> @Moshex It's a shame it doesn't actually fix the iOS 16 issues.

I agree but at least it's the same usable as the last version 3 package
