### ISSUE TITLE
Build and distrubite does not support msixbundle

### ISSUE THREAD

**Issue by curtisconner** [microsoft/appcenter#350]
I cant use the system currently since we cant distrubite the msixbundle

**Comment by winnieli1208** [comment]
@curtisconner - this is known bug we're tracking internally. I don't have an ETA on when this will be fixed but I'll update you when I have more details. Thanks for your patience and I apologize for the inconvenience!

**Comment by youngbupark** [comment]
@curtisconner - We have fixed this bug now. Please try to build and distribute your app. Please let us know if you have any problem. Thanks for your patience.

**Comment by curtisconner** [comment]
So I just tried it and I still can't get the build to deploy to the msappcenter

here is the error I get still

==============================================================================
Task         : App Center Distribute
Description  : Distribute app builds to testers and users via App Center
Version      : 3.150.1
Author       : Microsoft Corporation
Help         : For help with this task, visit the Visual Studio App Center [support site](https://aka.ms/appcentersupport/).
==============================================================================
##[error]Error: form-data: EISDIR: illegal operation on a directory, read
##[section]Finishing: Create distribution
##[section]Starting: Checkout
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================

**Comment by DennisPan** [comment]
@curtisconner We only addressed the case of manual distribution (from App Center portal, distribute from a build). Will take a look at the automatic distribute scenario (using Azure DevOps task)

**Comment by youngbupark** [comment]
@curtisconner - We fixed automatic distribution scenario issue for .msixbundle and validated not only automatic but also manual distribution scenarios. In order to apply the fix, please **save build configuration again** on the branch before queuing the build. Please let us know if you have a problem again.

**Comment by curtisconner** [comment]
Wow works great thanks
