### ISSUE TITLE
Build aways get canceled

### ISSUE THREAD

**Issue by matheusmelato** [microsoft/appcenter#746]
I'm starting to use AppCenter build tool but all generated builds are getting canceled right after it required.

To begin i've followed the [DOCS](https://docs.microsoft.com/en-us/appcenter/build/xamarin/) instructions and connect my AppCenter app to a GitHub repository, selected the project to build with all possible configurations (Debug/Release/Ad-hoc) but it kept always getting canceled status.

The build is canceled right after it has requested.

![image](https://user-images.githubusercontent.com/30476613/61538803-8e977500-aa10-11e9-917f-f8c64c97c372.png)

![image](https://user-images.githubusercontent.com/30476613/61538832-99520a00-aa10-11e9-902c-0af1cfc8d3cf.png)

**Comment by nrajpurkar** [comment]
Hi @matheusmelato, can you reach out to App Center support so we can follow up here and better troubleshoot with you directly? Thanks!

**Comment by matheusmelato** [comment]
> Hi @matheusmelato, can you reach out to App Center support so we can follow up here and better troubleshoot with you directly? Thanks!

Hi @nrajpurkar! I didn't notice that has a support chat there! I will send a message there, thanks!

**Comment by DennisPan** [comment]
@matheusmelato Thanks for reaching out. This issues should be fixed now. Let us now if you see anything else.

**Comment by adminvrbl** [comment]
Does anyone know what was the issue and fix? I am facing same issue.

**Comment by GeorgeFean** [comment]
Still having this issue on android build of React Native, any updates ?

**Comment by juanpgallardo** [comment]
@matheusmelato, @nilofer this is happening to me now for some of my apps. Any ideas of what to do when this happens? It doesn't show any error message and it doesn't leave any trace on the log. Any help would be appreciated. Thanks!

**Comment by IljaCuvasov** [comment]
Not sure why this ticket is closed as this has also been happening to us for the past several weeks

**Comment by KarimovAbdullo** [comment]
In React Native, the same issue occurs on Android as well. After I press build, it automatically gets 'canceled'. In my other projects, everything is fine, but in this new project, I'm facing this problem. Please take a look
