### ISSUE TITLE
Xamarin.UITest Android: POST Fails to '/start-application' and test does not start executing

### ISSUE THREAD

**Issue by pontusntengnas** [microsoft/appcenter#849]
**What App Center service does this affect?**
Xamarin.UITest

**Describe the bug**
When running UI tests on a Xamarin.Forms Android app on emulator they rarely start. The app itself is launched on the emulator but then it waits for some time without starting to execute the test to eventually fail with error message `POST Failed`. This does not happen on iOS at all and sometimes it works on Android as well so it is not always happening but very often.

When investing the logs I found that it is failing in the process of sending HTTP Posts. First it sends a successful request to `/ping` and gets _pong_ as response. Then it sends a request to `/ready` and the response is `200 OK`. 

Then it fails when POST:ing to `/start-application` (the application is though already started when this is done) without really telling why. To investigate I made the same request with Curl and got a stacktrace which says a null reference exception has occured: 

```curl -X POST http://127.0.0.1:53486/start-application -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 53486 (#0)
> POST /start-application HTTP/1.1
> Host: 127.0.0.1:53486
> User-Agent: curl/7.54.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Internal Server Error 
< Content-Type: application/json;charset=utf-8
< Date: Thu, 8 Aug 2019 13:23:19 GMT
< 
* Closing connection 0
{"reason":"Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference","detail":"java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference\n\tat java.io.StringReader.<init>(StringReader.java:50)\n\tat sh.calaba.org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:636)\n\tat sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:129)\n\tat sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)\n\tat java.lang.Thread.run(Thread.java:764)\n","outcome":"ERROR"}
```

**To Reproduce**

Config:
- Xamarin.UITest - 3.0.3
- NUnit - 3.12.0

1. Run a UI test on Android.
= 8 out of 10 times it fails with this error.

**Expected behavior**
The test to start executing.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.14.5

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Pie 9.0 - API 28

**Comment by amchew** [comment]
Thanks for posting @pontusntengnas! @Oddj0b or @King-of-Spades would you mind taking a look?

**Comment by ahanag22** [comment]
Can you send over your full version information from the IDEs here:
"Visual Studio -> About Visual Studio -> Show Details -> Copy Information" ?

Are you able to reproduce the symptoms using this sample? https://github.com/King-of-Spades/AppCenter-Samples/tree/master/Xamarin.UITest/UITestDemo

**Comment by pontusntengnas** [comment]
Sorry but I was running this on a quite old and slow computer when experiencing this problem. After switching to a faster one I do no longer have this issue.

**Comment by Oddj0b** [comment]
Sounds like this is solved.

Ha en bra dag @pontusntengnas

**Comment by pontusntengnas** [comment]
Well I guess the problem still exists but at least I managed to work around it with a new computer.

**Comment by King-of-Spades** [comment]
@pontusntengnas If you're concerned/expecting that it should be able to work on the older system, then it'd be good if you can share the details @ahanag22 detailed in her comment for both your old system and the working system. 

It's possible, if your system is old enough; that it _might_ be out of scope for support, but it might not be easy to determine that precisely because it depends on what tooling is hitting what limitation. (For example, Xamarin.UITest doesn't explicitly define a minimum OS version, but I believe Visual Studio does...so for most practical purposes VS would be the limiting factor there.)

**Comment by IlyaBausovAkvelon** [comment]
@rafageist Hi!
Thank you for your report. Seems like the issue is happening in calabash-android-server which is a public repo. You can try to check it.

I would like to ask you about your configuration of device. What Android version you are using?
