### ISSUE TITLE
iOS Code Signing problems on NEW app center build configurations only

### ISSUE THREAD

**Issue by henduck** [microsoft/appcenter#940]
I'm having code signing troubles on a NEW app center build instance. I'll say up front: I've confirmed this is NOT an issue with either my signing certificate or provisioning profile, as I am using the exact cert and profile without issue on both local builds AND on **_other app center builds that were set up several months ago and running without issue since_**.

The exact error being reported is:
```
"/Users/vsts/agent/2.155.1/work/1/s/iOS/Redacted.iOS/Redacted.iOS.csproj" (Rebuild target) (1) ->
(_DetectSigningIdentity target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(645,3): error : No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com. [/Users/vsts/agent/2.155.1/work/1/s/iOS/Redacted/Redacted.iOS.csproj]
```

Since I have other (older) MS App Center builds which DO work set up on the same codebase, same bundle id, same cert, same profile, I figured I'd examine any differences between the two. I've been able to identify only two differences between them that might be relevant:

1) When pulling the build config details from the AppCenter REST API (_GET /v0.1/apps/{owner_name}/{app_name}/branches/{branch}/config_), the 'xcode' section of the response differs in the following way:

Old App Instance (Which works):
"xcode": {
  "certificatePassword": "__protected__",
  "certificateFilename": "MyCertificate.p12",
  "provisioningProfileFilename": "MyProfile.mobileprovision",
  "xcodeVersion": "10.2.1"
}

New App Instance (Which doesn't work):
"xcode": {
  "certificatePassword": "__protected__",
  "certificateFilename": "MyCertificate.p12",
  "provisioningProfileFilename": "MyProfile.mobileprovision",
  "certificateFileId": "GUID-Redacted",
  "provisioningProfileFileId": "GUID Redacted",
  "xcodeVersion": "10.2.1"
}
_(some details redacted for customer privacy reasons, of course, but note the addition of the 'certificateFileId' and 'provisioningProfileFileId' fields in the newer build config)_

2) The set of build steps outlined in the build logs downloaded for each environment is significantly different. Notably, the certificate/profile-related steps are named differently and in a different place in the sequence. Hard to say if/why this would make any difference though, since the profile is manually provided in the build config.

![BuildLogs](https://f001.backblazeb2.com/file/jms-photos-backup/BuildLogs_OldVsNew.png)

It might also be worth noting that our Info.plist gets updated in the iOS/appcenter-pre-build.sh script to update its BundleID. This has been this way for a long time, and worked fine in our existing app center builds... so not sure why that would be any different here, but I'm out of ideas to troubleshoot this.

Has there been some change to how iOS builds work over the last couple weeks, such that old builds would continue to work but new ones wouldn't???

**Comment by henduck** [comment]
Just to close the loop on this.... we are now building again. Just had to change the iOS csproj so that both the Signing Identity and Provisioning Profile are set to 'Automatic' rather than any specific values for the Release/iPhone configuration. And more specifically, the signing identity must be set to **Distribution (Automatic)**   Anything else, and the build would fail at the signing step.

It's worth noting that this was not the case previously. (same exact codebase/branch builds successfully when app center build configuration is _cloned from an old one_ rather than a newly created configuration)

**Comment by mmarandici** [comment]
I am experiencing exactly the same issue with newly configured builds.

**Comment by school-today** [comment]
I have the same issue. Old builds ok, but new with same configuration - throws an error.

**Comment by evkhramkov** [comment]
@school-today @mmarandici we deployed a fix for that, now newly configured branches should work without any issues.
If you have any broken branch configuration just re-save it.

**Comment by tindn** [comment]
@evkhramkov I'm still getting the same error. I've tried everything suggested here. Confirmed that the same provisioning profile and cert works when built locally.

**Comment by evkhramkov** [comment]
@tindn could you please reach out to App Center support, so we can work with your issue more closely
